# Generated by Django 5.0.4 on 2024-04-06 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.phonenumber'),
        ),
    ]
